# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-16 14:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0020_old_tree_cleanup'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeMainInfo',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='resume_main_info_resumemaininfo', serialize=False, to='cms.CMSPlugin')),
                ('label', models.CharField(blank=True, max_length=200)),
                ('address_one', models.CharField(blank=True, max_length=200)),
                ('address_two', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=11)),
                ('email', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
