# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-16 15:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume_main_info', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resumemaininfo',
            old_name='address_one',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='resumemaininfo',
            name='address_two',
        ),
    ]
